# Generated by Django 3.2.13 on 2023-05-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежда'},
        ),
    ]
